# Funding platforms for LabOS
# See: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

github: YUANXICHE98
custom: ["https://etherscan.io/address/0xc6B4720835E6C3CB58618B4df26B64F595C30202"]
